// <auto-generated />
using System;
using GridCore.Modules.Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Finance.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260825043826_WP26_JournalEntries")]
    partial class WP26_JournalEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Finance.Features.ChartOfAccounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_code");

                    b.ToTable("accounts", "finance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7051-8175-845988f13f61"),
                            Code = "1000",
                            Name = "Cash at bank",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7b98-a8ca-390581b72629"),
                            Code = "1100",
                            Name = "Accounts receivable",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7037-a7df-af26abe1265b"),
                            Code = "1300",
                            Name = "Inventory",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-75fd-ac96-3805de594b61"),
                            Code = "1400",
                            Name = "Utility plant in service",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-71a8-b544-cf93c245178c"),
                            Code = "2000",
                            Name = "Accounts payable",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f51-b1ea-0c5a3e7f4c5f"),
                            Code = "2100",
                            Name = "Customer deposits",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f83-b5d2-a98f83f0aed5"),
                            Code = "2200",
                            Name = "Accrued liabilities",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7176-aeb3-1e601c3877c8"),
                            Code = "3000",
                            Name = "Retained earnings",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7090-9470-20e033534635"),
                            Code = "4000",
                            Name = "Utility revenue",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7989-8c7b-b333c6ad353c"),
                            Code = "4100",
                            Name = "Connection and service fees",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7e52-a0c4-102d65865bde"),
                            Code = "4200",
                            Name = "Late payment fees",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f8e-b4b7-2b6e0c9e88b3"),
                            Code = "5000",
                            Name = "Purchased power",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7299-806d-517825c0529d"),
                            Code = "5100",
                            Name = "Maintenance and repairs",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7cf6-9ce9-e7aca4e0f11b"),
                            Code = "5200",
                            Name = "Materials and supplies",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-70a1-8afd-46c582f82b4c"),
                            Code = "5900",
                            Name = "Bad debt expense",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Finance.Features.Journal.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("entry_number");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<DateOnly>("PostedOn")
                        .HasColumnType("date")
                        .HasColumnName("posted_on");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_credits");

                    b.Property<decimal>("TotalDebits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debits");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_journal_entries_customer");

                    b.HasIndex("EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_entries_number");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_entries_event");

                    b.HasIndex("PostedOn")
                        .HasDatabaseName("ix_journal_entries_posted_on");

                    b.HasIndex("ServiceAccountId")
                        .HasDatabaseName("ix_journal_entries_service_account");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_journal_entries_source");

                    b.ToTable("journal_entries", "finance");
                });

            modelBuilder.Entity("GridCore.Modules.Finance.Features.Journal.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_lines_account");

                    b.HasIndex("JournalEntryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_lines_sequence");

                    b.ToTable("journal_lines", "finance");
                });

            modelBuilder.Entity("GridCore.Modules.Finance.Features.Journal.JournalLine", b =>
                {
                    b.HasOne("GridCore.Modules.Finance.Features.ChartOfAccounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_account");

                    b.HasOne("GridCore.Modules.Finance.Features.Journal.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_entry");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GridCore.Modules.Finance.Features.Journal.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
