// <auto-generated />
using System;
using GridCore.Modules.Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Finance.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Finance.Features.ChartOfAccounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_code");

                    b.ToTable("accounts", "finance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7051-8175-845988f13f61"),
                            Code = "1000",
                            Name = "Cash at bank",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7b98-a8ca-390581b72629"),
                            Code = "1100",
                            Name = "Accounts receivable",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7037-a7df-af26abe1265b"),
                            Code = "1300",
                            Name = "Inventory",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-75fd-ac96-3805de594b61"),
                            Code = "1400",
                            Name = "Utility plant in service",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-71a8-b544-cf93c245178c"),
                            Code = "2000",
                            Name = "Accounts payable",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f51-b1ea-0c5a3e7f4c5f"),
                            Code = "2100",
                            Name = "Customer deposits",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f83-b5d2-a98f83f0aed5"),
                            Code = "2200",
                            Name = "Accrued liabilities",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7176-aeb3-1e601c3877c8"),
                            Code = "3000",
                            Name = "Retained earnings",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7090-9470-20e033534635"),
                            Code = "4000",
                            Name = "Utility revenue",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7989-8c7b-b333c6ad353c"),
                            Code = "4100",
                            Name = "Connection and service fees",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7e52-a0c4-102d65865bde"),
                            Code = "4200",
                            Name = "Late payment fees",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7f8e-b4b7-2b6e0c9e88b3"),
                            Code = "5000",
                            Name = "Purchased power",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7299-806d-517825c0529d"),
                            Code = "5100",
                            Name = "Maintenance and repairs",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7cf6-9ce9-e7aca4e0f11b"),
                            Code = "5200",
                            Name = "Materials and supplies",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-70a1-8afd-46c582f82b4c"),
                            Code = "5900",
                            Name = "Bad debt expense",
                            Type = "Expense"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
