// <auto-generated />
using System;
using GridCore.Modules.Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260824055956_WP14_Items")]
    partial class WP14_Items
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("item_code");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer_part_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_stock_items_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_stock_items_is_active");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_items_item_code");

                    b.HasIndex("ManufacturerPartNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_items_manufacturer_part_number");

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastMovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_moved_at");

                    b.Property<decimal>("MinimumQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("minimum_quantity");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_on_hand");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_levels");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_stock_levels_warehouse_id");

                    b.HasIndex("StockItemId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_levels_item_warehouse");

                    b.ToTable("stock_levels", "inventory");
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("movement_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_change");

                    b.Property<decimal>("QuantityOnHandAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_on_hand_after");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("MovementType")
                        .HasDatabaseName("ix_stock_movements_movement_type");

                    b.HasIndex("StockItemId")
                        .HasDatabaseName("ix_stock_movements_stock_item_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_stock_movements_warehouse_id");

                    b.ToTable("stock_movements", "inventory");
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouses_code");

                    b.ToTable("warehouses", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7583-ad03-8fbf7e6529e6"),
                            Code = "MAIN",
                            IsActive = true,
                            Location = "1 Utility Way, Central depot",
                            Name = "Main store"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-74a4-89fb-589a0a731112"),
                            Code = "NORTH",
                            IsActive = true,
                            Location = "45 Kestrel Road, North district",
                            Name = "North depot"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7d5d-9d3e-2a1ea67ec09e"),
                            Code = "YARD",
                            IsActive = true,
                            Location = "Substation 7, East industrial park",
                            Name = "Substation yard"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockLevel", b =>
                {
                    b.HasOne("GridCore.Modules.Inventory.Features.Items.StockItem", null)
                        .WithMany("Levels")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_stock_item");

                    b.HasOne("GridCore.Modules.Inventory.Features.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_warehouse");
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockMovement", b =>
                {
                    b.HasOne("GridCore.Modules.Inventory.Features.Items.StockItem", null)
                        .WithMany("Movements")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_stock_item");

                    b.HasOne("GridCore.Modules.Inventory.Features.Warehouses.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_warehouse");
                });

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Items.StockItem", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
