// <auto-generated />
using System;
using GridCore.Modules.Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Inventory.Features.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_warehouses_code");

                    b.ToTable("warehouses", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7583-ad03-8fbf7e6529e6"),
                            Code = "MAIN",
                            IsActive = true,
                            Location = "1 Utility Way, Central depot",
                            Name = "Main store"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-74a4-89fb-589a0a731112"),
                            Code = "NORTH",
                            IsActive = true,
                            Location = "45 Kestrel Road, North district",
                            Name = "North depot"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7d5d-9d3e-2a1ea67ec09e"),
                            Code = "YARD",
                            IsActive = true,
                            Location = "Substation 7, East industrial park",
                            Name = "Substation yard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
