// <auto-generated />
using System;
using GridCore.Modules.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Billing.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260824020549_WP08_RatePlans")]
    partial class WP08_RatePlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal>("MonthlyServiceCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_service_charge");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_type");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_rate_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plans_code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plans_default")
                        .HasFilter("is_default");

                    b.ToTable("rate_plans", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7eb4-b30b-55d2b561d9bb"),
                            Code = "RES-STD",
                            Currency = "USD",
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            IsDefault = true,
                            MonthlyServiceCharge = 12.50m,
                            Name = "Residential standard",
                            ServiceType = "Electricity",
                            UnitOfMeasure = "kWh"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7440-82af-b70efb8671c9"),
                            Code = "COM-STD",
                            Currency = "USD",
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            IsDefault = false,
                            MonthlyServiceCharge = 45.00m,
                            Name = "Commercial standard",
                            ServiceType = "Electricity",
                            UnitOfMeasure = "kWh"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlanTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("RatePerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate_per_unit");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_plan_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal?>("UpToUnits")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("up_to_units");

                    b.HasKey("Id")
                        .HasName("pk_rate_plan_tiers");

                    b.HasIndex("RatePlanId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plan_tiers_sequence");

                    b.ToTable("rate_plan_tiers", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7545-8b53-76122bf03982"),
                            RatePerUnit = 0.1145m,
                            RatePlanId = new Guid("01a03111-1c00-7eb4-b30b-55d2b561d9bb"),
                            Sequence = 1,
                            UpToUnits = 500m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-723d-bcd7-80ea4ecbf39c"),
                            RatePerUnit = 0.1385m,
                            RatePlanId = new Guid("01a03111-1c00-7eb4-b30b-55d2b561d9bb"),
                            Sequence = 2,
                            UpToUnits = 1000m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7b3f-85a9-3f4876dbe728"),
                            RatePerUnit = 0.1620m,
                            RatePlanId = new Guid("01a03111-1c00-7eb4-b30b-55d2b561d9bb"),
                            Sequence = 3
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7ddb-9d30-63f09b9c7610"),
                            RatePerUnit = 0.1290m,
                            RatePlanId = new Guid("01a03111-1c00-7440-82af-b70efb8671c9"),
                            Sequence = 1,
                            UpToUnits = 2000m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7c6f-9b8c-d303bdc8e7c9"),
                            RatePerUnit = 0.1105m,
                            RatePlanId = new Guid("01a03111-1c00-7440-82af-b70efb8671c9"),
                            Sequence = 2
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlanTier", b =>
                {
                    b.HasOne("GridCore.Modules.Billing.Features.RatePlans.RatePlan", null)
                        .WithMany("Tiers")
                        .HasForeignKey("RatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_plan_tiers_rate_plans");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlan", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
