// <auto-generated />
using System;
using GridCore.Modules.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Billing.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260826232234_WP219_LateCharges")]
    partial class WP219_LateCharges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("AdjustmentTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("adjustment_total");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bill_number");

                    b.Property<decimal>("Consumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("consumption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CurrentReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("current_reading");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CycleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cycle_code");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee_amount");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("MeterNumber")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("meter_number");

                    b.Property<Guid?>("MeterReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_reading_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal?>("PreviousReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("previous_reading");

                    b.Property<string>("RatePlanCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rate_plan_code");

                    b.Property<DateOnly?>("RatePlanEffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("rate_plan_effective_from");

                    b.Property<Guid?>("RatePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_plan_id");

                    b.Property<string>("RatePlanName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rate_plan_name");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("status_reason");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("BillNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_bills_bill_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bills_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bills_status");

                    b.HasIndex("ServiceAccountId", "CycleCode")
                        .IsUnique()
                        .HasDatabaseName("ux_bills_account_cycle");

                    b.ToTable("bills", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.BillAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountDueAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_due_after");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_bill_adjustments");

                    b.HasIndex("BillId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_bill_adjustments_sequence");

                    b.ToTable("bill_adjustments", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.BillLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<decimal?>("RatePerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate_per_unit");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int?>("TierSequence")
                        .HasColumnType("integer")
                        .HasColumnName("tier_sequence");

                    b.Property<decimal?>("Units")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_bill_lines");

                    b.HasIndex("BillId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_bill_lines_sequence");

                    b.ToTable("bill_lines", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Delinquency.LateChargeAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_charge_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<DateOnly>("AssessedOn")
                        .HasColumnType("date")
                        .HasColumnName("assessed_on");

                    b.Property<decimal>("BasisAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("basis_amount");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bill_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_past_due");

                    b.Property<Guid>("FeeScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_schedule_id");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_late_charge_assessments");

                    b.HasIndex("BillId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ux_late_charge_assessments_bill_period");

                    b.HasIndex("ServiceAccountId", "PeriodStart")
                        .HasDatabaseName("ix_late_charge_assessments_account_period");

                    b.ToTable("late_charge_assessments", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Fees.AccountCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("basis");

                    b.Property<decimal?>("BasisAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("basis_amount");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bill_number");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("fee_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("description");

                    b.Property<Guid>("FeeScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_schedule_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<DateOnly>("RaisedOn")
                        .HasColumnType("date")
                        .HasColumnName("raised_on");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("ScheduleEffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("schedule_effective_from");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_account_charges");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_account_charges_bill_id");

                    b.HasIndex("ServiceAccountId", "Status")
                        .HasDatabaseName("ix_account_charges_account_status");

                    b.ToTable("account_charges", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Fees.FeeScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("basis");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.HasKey("Id")
                        .HasName("pk_fee_schedule");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ux_fee_schedule_code_effective");

                    b.ToTable("fee_schedule", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7e9d-876d-604b24264e33"),
                            Amount = 135.00m,
                            Basis = "Flat",
                            Code = "ServiceConnection",
                            Currency = "USD",
                            Description = "Levied once when supply is established at a premise, covering the meter and the service drop. Demo figure following CUC's published customer-service information; that schedule changes without notice, so this is a demo schedule and not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Service connection fee",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7726-bbcd-93fad896309f"),
                            Amount = 50.00m,
                            Basis = "Flat",
                            Code = "Reconnection",
                            Currency = "USD",
                            Description = "Levied when supply is restored after it was cut for non-payment. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Reconnection fee",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7f1a-99ee-1a8a6b1ee323"),
                            Amount = 25.00m,
                            Basis = "Flat",
                            Code = "ReturnedPayment",
                            Currency = "USD",
                            Description = "Levied when a payment that settled is returned unpaid by the bank. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Returned payment fee",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7e49-8b5b-7db00eb0ae92"),
                            Amount = 75.00m,
                            Basis = "Flat",
                            Code = "MeterTest",
                            Currency = "USD",
                            Description = "Levied when a customer asks for their meter to be tested. Refundable where the meter is found to be faulty, which is WP-3.8's business rather than the schedule's. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Meter test fee",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7935-ae46-cb50fc10e937"),
                            Amount = 50.00m,
                            Basis = "Flat",
                            Code = "Inspection",
                            Currency = "USD",
                            Description = "Levied for inspecting a customer's installation before supply is established. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Installation inspection fee",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7903-9ba4-0e2b130bef15"),
                            Amount = 550.00m,
                            Basis = "Flat",
                            Code = "UnauthorizedConnection",
                            Currency = "USD",
                            Description = "The penalty for taking supply without an account or interfering with a meter, levied on top of an estimate of the unbilled usage. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Unauthorized connection penalty",
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7f47-8dfa-fb2ea961cf60"),
                            Basis = "Rate",
                            Code = "LateCharge",
                            Currency = "USD",
                            Description = "One per cent per month of the past-due balance, assessed once per bill per month while it remains unpaid. Demo figure following CUC's published customer-service information and the delinquency regime of CNMI Public Law 16-17; that schedule changes without notice, so this is a demo rate and not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            Name = "Late payment charge",
                            Rate = 0.0100m,
                            ServiceType = "Electricity"
                        },
                        new
                        {
                            Id = new Guid("01a03b5d-d400-7e42-80c3-b9f9b4e18513"),
                            Amount = 60.00m,
                            Basis = "Flat",
                            Code = "Reconnection",
                            Currency = "USD",
                            Description = "Republished figure, effective 1 July 2026. Demo figure following CUC's published customer-service information; not an authoritative charge.",
                            EffectiveFrom = new DateOnly(2026, 7, 1),
                            Name = "Reconnection fee",
                            ServiceType = "Electricity"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.AccountRatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("RatePlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rate_plan_code");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_account_rate_plans");

                    b.HasIndex("ServiceAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_account_rate_plans_account");

                    b.ToTable("account_rate_plans", "billing");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal>("MonthlyServiceCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_service_charge");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_type");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_rate_plans");

                    b.HasIndex("Code", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plans_code_effective");

                    b.HasIndex("ServiceType", "IsDefault", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plans_default_effective")
                        .HasFilter("is_default");

                    b.ToTable("rate_plans", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-751c-a792-94a84d62db9a"),
                            Code = "RES-STD",
                            Currency = "USD",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            IsDefault = true,
                            MonthlyServiceCharge = 12.50m,
                            Name = "Residential standard",
                            ServiceType = "Electricity",
                            UnitOfMeasure = "kWh"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7b1b-a2bb-cd85284d214f"),
                            Code = "COM-STD",
                            Currency = "USD",
                            EffectiveFrom = new DateOnly(2025, 1, 1),
                            IsDefault = false,
                            MonthlyServiceCharge = 45.00m,
                            Name = "Commercial standard",
                            ServiceType = "Electricity",
                            UnitOfMeasure = "kWh"
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7c54-a54e-2d4921568a7c"),
                            Code = "RES-STD",
                            Currency = "USD",
                            EffectiveFrom = new DateOnly(2026, 7, 1),
                            IsDefault = true,
                            MonthlyServiceCharge = 13.75m,
                            Name = "Residential standard",
                            ServiceType = "Electricity",
                            UnitOfMeasure = "kWh"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlanTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("RatePerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate_per_unit");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_plan_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal?>("UpToUnits")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("up_to_units");

                    b.HasKey("Id")
                        .HasName("pk_rate_plan_tiers");

                    b.HasIndex("RatePlanId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_rate_plan_tiers_sequence");

                    b.ToTable("rate_plan_tiers", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03111-1c00-7c16-96c8-173e40ae8222"),
                            RatePerUnit = 0.1145m,
                            RatePlanId = new Guid("01a03111-1c00-751c-a792-94a84d62db9a"),
                            Sequence = 1,
                            UpToUnits = 500m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7c1b-bc31-49b94fcf81a8"),
                            RatePerUnit = 0.1385m,
                            RatePlanId = new Guid("01a03111-1c00-751c-a792-94a84d62db9a"),
                            Sequence = 2,
                            UpToUnits = 1000m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7bdb-958f-15b5c5a3cc68"),
                            RatePerUnit = 0.1620m,
                            RatePlanId = new Guid("01a03111-1c00-751c-a792-94a84d62db9a"),
                            Sequence = 3
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-73e3-9a13-986fb86fc536"),
                            RatePerUnit = 0.1290m,
                            RatePlanId = new Guid("01a03111-1c00-7b1b-a2bb-cd85284d214f"),
                            Sequence = 1,
                            UpToUnits = 2000m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-74fb-bae8-d5da5f7394c3"),
                            RatePerUnit = 0.1105m,
                            RatePlanId = new Guid("01a03111-1c00-7b1b-a2bb-cd85284d214f"),
                            Sequence = 2
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7002-806d-6835aacf0b0c"),
                            RatePerUnit = 0.1225m,
                            RatePlanId = new Guid("01a03111-1c00-7c54-a54e-2d4921568a7c"),
                            Sequence = 1,
                            UpToUnits = 500m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7d31-98e9-32d3927853be"),
                            RatePerUnit = 0.1480m,
                            RatePlanId = new Guid("01a03111-1c00-7c54-a54e-2d4921568a7c"),
                            Sequence = 2,
                            UpToUnits = 1000m
                        },
                        new
                        {
                            Id = new Guid("01a03111-1c00-7ffe-a8fb-2c329fdfad51"),
                            RatePerUnit = 0.1735m,
                            RatePlanId = new Guid("01a03111-1c00-7c54-a54e-2d4921568a7c"),
                            Sequence = 3
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.BillAdjustment", b =>
                {
                    b.HasOne("GridCore.Modules.Billing.Features.Bills.Bill", null)
                        .WithMany("Adjustments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bill_adjustments_bill");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.BillLine", b =>
                {
                    b.HasOne("GridCore.Modules.Billing.Features.Bills.Bill", null)
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bill_lines_bill");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlanTier", b =>
                {
                    b.HasOne("GridCore.Modules.Billing.Features.RatePlans.RatePlan", null)
                        .WithMany("Tiers")
                        .HasForeignKey("RatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_plan_tiers_rate_plans");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.Bills.Bill", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GridCore.Modules.Billing.Features.RatePlans.RatePlan", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
