// <auto-generated />
using System;
using GridCore.Modules.Customers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Customers.Data.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260826232312_WP219_Delinquency")]
    partial class WP219_Delinquency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Applications.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ServiceApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_application_id");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_application_documents");

                    b.HasIndex("ServiceApplicationId")
                        .HasDatabaseName("ix_application_documents_application_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_documents_storage_key");

                    b.ToTable("application_documents", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Applications.ServiceApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("application_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedById")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("DecidedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("decided_by_name");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("decision_notes");

                    b.Property<string>("DecisionReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision_reason_code");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ReplacesApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaces_application_id");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_started_at");

                    b.Property<string>("ReviewerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewer_name");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_location_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("submitted_by_id");

                    b.Property<string>("SubmittedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("submitted_by_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("application_type");

                    b.HasKey("Id")
                        .HasName("pk_service_applications");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_service_applications_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_service_applications_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_applications_status");

                    b.HasIndex("ServiceLocationId", "ServiceType")
                        .IsUnique()
                        .HasDatabaseName("ux_service_applications_open_premise")
                        .HasFilter("\"status\" IN ('Submitted', 'UnderReview')");

                    b.ToTable("service_applications", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.ContactMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_contact_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_methods");

                    b.HasIndex("CustomerContactId", "Kind")
                        .HasDatabaseName("ix_contact_methods_contact_kind");

                    b.ToTable("contact_methods", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsAuthorisedToDiscuss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authorised_to_discuss");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Relationship")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relationship");

                    b.HasKey("Id")
                        .HasName("pk_customer_contacts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_contacts_customer");

                    b.ToTable("customer_contacts", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset?>("ClassChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("class_changed_at");

                    b.Property<DateOnly?>("ClassEffectiveOn")
                        .HasColumnType("date")
                        .HasColumnName("class_effective_on");

                    b.Property<string>("ContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_name");

                    b.Property<decimal>("DepositHeld")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_held");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<DateOnly?>("StatusEffectiveOn")
                        .HasColumnType("date")
                        .HasColumnName("status_effective_on");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_account_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_customers_status");

                    b.ToTable("customers", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Delinquency.DunningNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("ArrearsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("arrears_amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_past_due");

                    b.Property<Guid>("DunningStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("dunning_step_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<string>("NoticeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("notice_type");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<DateOnly>("ServedOn")
                        .HasColumnType("date")
                        .HasColumnName("served_on");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<int>("WaitingPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("waiting_period_days");

                    b.HasKey("Id")
                        .HasName("pk_dunning_notices");

                    b.HasIndex("ServiceAccountId", "NoticeType", "ServedOn")
                        .HasDatabaseName("ix_dunning_notices_account_type_served");

                    b.ToTable("dunning_notices", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Delinquency.DunningStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<int>("DaysPastDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_past_due");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<decimal>("MinimumArrears")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_arrears");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NoticeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("notice_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("WaitingPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("waiting_period_days");

                    b.HasKey("Id")
                        .HasName("pk_dunning_steps");

                    b.HasIndex("NoticeType")
                        .IsUnique()
                        .HasDatabaseName("ux_dunning_steps_notice_type");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_dunning_steps_sequence");

                    b.ToTable("dunning_steps", "customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a04084-3000-7175-bbbf-a17e6e3d1550"),
                            Currency = "USD",
                            DaysPastDue = 10,
                            Message = "Your account is past due. Please pay the outstanding balance to avoid further action. If you have already paid, thank you — please disregard this notice. Demo wording and demo timing following CUC's published customer-service information; not an authoritative notice.",
                            MinimumArrears = 10.00m,
                            Name = "Payment reminder",
                            NoticeType = "Reminder",
                            Sequence = 1,
                            WaitingPeriodDays = 0
                        },
                        new
                        {
                            Id = new Guid("01a04084-3000-7be2-b5b2-f1676c455930"),
                            Currency = "USD",
                            DaysPastDue = 30,
                            Message = "Your account is delinquent. Pay the outstanding balance in full, or contact Customer Service to arrange payment, to avoid disconnection of service. Demo wording and demo timing following CUC's published customer-service information; not an authoritative notice.",
                            MinimumArrears = 25.00m,
                            Name = "Notice of delinquency",
                            NoticeType = "Delinquency",
                            Sequence = 2,
                            WaitingPeriodDays = 0
                        },
                        new
                        {
                            Id = new Guid("01a04084-3000-7913-a281-a6a386bcf4df"),
                            Currency = "USD",
                            DaysPastDue = 45,
                            Message = "Service at this premise is scheduled for disconnection for non-payment. To avoid disconnection, pay the outstanding balance, or contact Customer Service to arrange payment, within ten days of the date of this notice. Any security deposit held will be applied to qualifying past-due amounts before service is disconnected. Demo wording and demo timing following CUC's published customer-service information and CNMI Public Law 16-17; not an authoritative notice.",
                            MinimumArrears = 50.00m,
                            Name = "Notice of disconnection",
                            NoticeType = "Disconnection",
                            Sequence = 3,
                            WaitingPeriodDays = 10
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Deposits.DepositEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bill_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsInterestBearing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interest_bearing");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_deposit_entries");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_deposit_entries_bill_id")
                        .HasFilter("\"bill_id\" IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_deposit_entries_customer_id");

                    b.ToTable("deposit_entries", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Notes.CustomerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("CorrectsNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrects_note_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("FollowUpOn")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_on");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LinkKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("link_kind");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedReference")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("linked_reference");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_notes");

                    b.HasIndex("CorrectsNoteId")
                        .HasDatabaseName("ix_customer_notes_corrects_note_id")
                        .HasFilter("\"corrects_note_id\" IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_notes_customer_id");

                    b.HasIndex("LinkKind", "LinkedEntityId")
                        .HasDatabaseName("ix_customer_notes_link")
                        .HasFilter("\"linked_entity_id\" IS NOT NULL");

                    b.HasIndex(new[] { "CustomerId" }, "ix_customer_notes_pinned")
                        .HasDatabaseName("ix_customer_notes_pinned")
                        .HasFilter("\"is_pinned\"");

                    b.ToTable("customer_notes", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Profile.CustomerProfile", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("BillDeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bill_delivery_channel");

                    b.Property<bool>("DunningNotices")
                        .HasColumnType("boolean")
                        .HasColumnName("dunning_notices");

                    b.Property<bool>("OutageNotices")
                        .HasColumnType("boolean")
                        .HasColumnName("outage_notices");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId")
                        .HasName("pk_customer_profiles");

                    b.ToTable("customer_profiles", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Registration.DepositRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_class");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<decimal>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_amount");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<int?>("UsageMonths")
                        .HasColumnType("integer")
                        .HasColumnName("usage_months");

                    b.Property<decimal?>("UsageRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("usage_rate");

                    b.HasKey("Id")
                        .HasName("pk_deposit_rules");

                    b.HasIndex("CustomerClass", "ServiceType")
                        .IsUnique()
                        .HasDatabaseName("ux_deposit_rules_class_service");

                    b.ToTable("deposit_rules", "customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03637-7800-7065-af71-6221df4735ea"),
                            Currency = "USD",
                            CustomerClass = "Residential",
                            Description = "Residential electricity: the greater of $75 and two months of average usage at $0.3200/kWh. Demonstration figures — CUC's published residential deposit and its energy rate both move, and neither is quoted here as authoritative.",
                            MinimumAmount = 75.00m,
                            ServiceType = "Electricity",
                            UsageMonths = 2,
                            UsageRate = 0.3200m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7896-beab-6e1fb5e65cfa"),
                            Currency = "USD",
                            CustomerClass = "Residential",
                            Description = "Residential water: the greater of $50 and two months of average usage at $2.5000 per cubic metre. Demonstration figures — the utility in this MVP distributes electricity only, and the water schedule exists so the module can express a service it does not yet supply.",
                            MinimumAmount = 50.00m,
                            ServiceType = "Water",
                            UsageMonths = 2,
                            UsageRate = 2.5000m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7a18-8779-ab6d1f2d9d9f"),
                            Currency = "USD",
                            CustomerClass = "Residential",
                            Description = "Residential gas: the greater of $50 and two months of average usage at $1.5000 per therm. Demonstration figures — GridCore declares gas as a service type and the demonstration utility does not distribute it; the rule exists so the schedule is complete.",
                            MinimumAmount = 50.00m,
                            ServiceType = "Gas",
                            UsageMonths = 2,
                            UsageRate = 1.5000m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7990-9709-6e7948af367d"),
                            Currency = "USD",
                            CustomerClass = "Residential",
                            Description = "Residential wastewater: a flat $30. Unmetered — there is no wastewater meter, so there is nothing to average and no usage basis to apply. Demonstration figure.",
                            MinimumAmount = 30.00m,
                            ServiceType = "Wastewater"
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7ff8-b74d-41c6cc4d344a"),
                            Currency = "USD",
                            CustomerClass = "Commercial",
                            Description = "Commercial electricity: the greater of $450 and two months of average usage at $0.3200/kWh. Demonstration figures — CUC's published commercial deposit and its energy rate both move, and neither is quoted here as authoritative.",
                            MinimumAmount = 450.00m,
                            ServiceType = "Electricity",
                            UsageMonths = 2,
                            UsageRate = 0.3200m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7d84-a36d-d09df560653d"),
                            Currency = "USD",
                            CustomerClass = "Commercial",
                            Description = "Commercial water: the greater of $250 and two months of average usage at $2.5000 per cubic metre. Demonstration figures — see the residential water rule.",
                            MinimumAmount = 250.00m,
                            ServiceType = "Water",
                            UsageMonths = 2,
                            UsageRate = 2.5000m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7159-991a-fed1e0114a6e"),
                            Currency = "USD",
                            CustomerClass = "Commercial",
                            Description = "Commercial gas: the greater of $250 and two months of average usage at $1.5000 per therm. Demonstration figures — see the residential gas rule.",
                            MinimumAmount = 250.00m,
                            ServiceType = "Gas",
                            UsageMonths = 2,
                            UsageRate = 1.5000m
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-73ce-aafd-d7d13f799782"),
                            Currency = "USD",
                            CustomerClass = "Commercial",
                            Description = "Commercial wastewater: a flat $150. Unmetered — there is no wastewater meter, so there is nothing to average and no usage basis to apply. Demonstration figure.",
                            MinimumAmount = 150.00m,
                            ServiceType = "Wastewater"
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTimeOffset?>("ServiceEndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_ended_at");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_location_id");

                    b.Property<DateTimeOffset?>("ServiceStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_started_at");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_service_accounts");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_service_accounts_account_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_service_accounts_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_accounts_status");

                    b.HasIndex("ServiceLocationId", "ServiceType")
                        .IsUnique()
                        .HasDatabaseName("ux_service_accounts_open_location")
                        .HasFilter("\"status\" <> 'Closed'");

                    b.ToTable("service_accounts", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccountHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_service_account_history");

                    b.HasIndex("ServiceAccountId")
                        .HasDatabaseName("ix_service_account_history_account_id");

                    b.ToTable("service_account_history", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("location_code");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_service_locations");

                    b.HasIndex("LocationCode")
                        .IsUnique()
                        .HasDatabaseName("ux_service_locations_location_code");

                    b.ToTable("service_locations", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Transitions.AccountTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DepositCarried")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_carried");

                    b.Property<Guid?>("DepositEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_entry_id");

                    b.Property<DateOnly>("EffectiveOn")
                        .HasColumnType("date")
                        .HasColumnName("effective_on");

                    b.Property<Guid?>("FromServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_service_account_id");

                    b.Property<string>("FromValue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_value");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ToServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_service_account_id");

                    b.Property<string>("ToValue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_value");

                    b.HasKey("Id")
                        .HasName("pk_account_transitions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_account_transitions_customer_id");

                    b.HasIndex("FromServiceAccountId")
                        .HasDatabaseName("ix_account_transitions_from_account")
                        .HasFilter("\"from_service_account_id\" IS NOT NULL");

                    b.HasIndex("ToServiceAccountId")
                        .HasDatabaseName("ix_account_transitions_to_account")
                        .HasFilter("\"to_service_account_id\" IS NOT NULL");

                    b.ToTable("account_transitions", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Applications.ApplicationDocument", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Applications.ServiceApplication", null)
                        .WithMany("Documents")
                        .HasForeignKey("ServiceApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_documents_application");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Applications.ServiceApplication", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_applications_customer");

                    b.HasOne("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", null)
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_applications_location");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.ContactMethod", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Contacts.CustomerContact", null)
                        .WithMany("Methods")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_methods_contact");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Deposits.DepositEntry", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposit_entries_customer");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Notes.CustomerNote", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Notes.CustomerNote", null)
                        .WithMany()
                        .HasForeignKey("CorrectsNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_notes_corrects");

                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_notes_customer");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Profile.CustomerProfile", b =>
                {
                    b.OwnsOne("GridCore.Modules.Customers.Features.ServiceLocations.Address", "MailingAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("mailing_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("mailing_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("mailing_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("mailing_region");

                            b1.HasKey("CustomerProfileCustomerId");

                            b1.ToTable("customer_profiles", "customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileCustomerId");
                        });

                    b.Navigation("MailingAddress");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_customer");

                    b.HasOne("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", null)
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_location");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccountHistoryEntry", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", null)
                        .WithMany("History")
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_history_account");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", b =>
                {
                    b.OwnsOne("GridCore.Modules.Customers.Features.ServiceLocations.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ServiceLocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_region");

                            b1.HasKey("ServiceLocationId");

                            b1.HasIndex("Region")
                                .HasDatabaseName("ix_service_locations_address_region");

                            b1.ToTable("service_locations", "customers");

                            b1.WithOwner()
                                .HasForeignKey("ServiceLocationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Transitions.AccountTransition", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_transitions_customer");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Applications.ServiceApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.CustomerContact", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
