// <auto-generated />
using System;
using GridCore.Modules.Customers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridCore.Modules.Customers.Data.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260826021333_WP213_CustomerNotes")]
    partial class WP213_CustomerNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.ContactMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_contact_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_methods");

                    b.HasIndex("CustomerContactId", "Kind")
                        .HasDatabaseName("ix_contact_methods_contact_kind");

                    b.ToTable("contact_methods", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsAuthorisedToDiscuss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authorised_to_discuss");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Relationship")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relationship");

                    b.HasKey("Id")
                        .HasName("pk_customer_contacts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_contacts_customer");

                    b.ToTable("customer_contacts", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("class");

                    b.Property<string>("ContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_name");

                    b.Property<decimal>("DepositHeld")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_held");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_account_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_customers_status");

                    b.ToTable("customers", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Deposits.DepositEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("bill_number");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsInterestBearing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interest_bearing");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_deposit_entries");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_deposit_entries_bill_id")
                        .HasFilter("\"bill_id\" IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_deposit_entries_customer_id");

                    b.ToTable("deposit_entries", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Notes.CustomerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("CorrectsNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrects_note_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("FollowUpOn")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_on");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LinkKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("link_kind");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedReference")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("linked_reference");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_notes");

                    b.HasIndex("CorrectsNoteId")
                        .HasDatabaseName("ix_customer_notes_corrects_note_id")
                        .HasFilter("\"corrects_note_id\" IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_notes_customer_id");

                    b.HasIndex("LinkKind", "LinkedEntityId")
                        .HasDatabaseName("ix_customer_notes_link")
                        .HasFilter("\"linked_entity_id\" IS NOT NULL");

                    b.HasIndex(new[] { "CustomerId" }, "ix_customer_notes_pinned")
                        .HasDatabaseName("ix_customer_notes_pinned")
                        .HasFilter("\"is_pinned\"");

                    b.ToTable("customer_notes", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Profile.CustomerProfile", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("BillDeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bill_delivery_channel");

                    b.Property<bool>("DunningNotices")
                        .HasColumnType("boolean")
                        .HasColumnName("dunning_notices");

                    b.Property<bool>("OutageNotices")
                        .HasColumnType("boolean")
                        .HasColumnName("outage_notices");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId")
                        .HasName("pk_customer_profiles");

                    b.ToTable("customer_profiles", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Registration.DepositRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_class");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_deposit_rules");

                    b.HasIndex("CustomerClass")
                        .IsUnique()
                        .HasDatabaseName("ux_deposit_rules_class");

                    b.ToTable("deposit_rules", "customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a03637-7800-7b13-b0b4-4a028a08b4e8"),
                            Amount = 75.00m,
                            Currency = "USD",
                            CustomerClass = "Residential",
                            Description = "One residential connection: two months of a typical household bill, refundable on close."
                        },
                        new
                        {
                            Id = new Guid("01a03637-7800-7a7d-8b76-34355f44b9d8"),
                            Amount = 450.00m,
                            Currency = "USD",
                            CustomerClass = "Commercial",
                            Description = "One commercial connection: two months of a small-premises bill, refundable on close."
                        });
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("account_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTimeOffset?>("ServiceEndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_ended_at");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_location_id");

                    b.Property<DateTimeOffset?>("ServiceStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_service_accounts");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_service_accounts_account_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_service_accounts_customer_id");

                    b.HasIndex("ServiceLocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_service_accounts_open_location")
                        .HasFilter("\"status\" <> 'Closed'");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_accounts_status");

                    b.ToTable("service_accounts", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccountHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_account_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_service_account_history");

                    b.HasIndex("ServiceAccountId")
                        .HasDatabaseName("ix_service_account_history_account_id");

                    b.ToTable("service_account_history", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("location_code");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_reason");

                    b.HasKey("Id")
                        .HasName("pk_service_locations");

                    b.HasIndex("LocationCode")
                        .IsUnique()
                        .HasDatabaseName("ux_service_locations_location_code");

                    b.ToTable("service_locations", "customers");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.ContactMethod", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Contacts.CustomerContact", null)
                        .WithMany("Methods")
                        .HasForeignKey("CustomerContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_methods_contact");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Deposits.DepositEntry", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposit_entries_customer");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Notes.CustomerNote", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Notes.CustomerNote", null)
                        .WithMany()
                        .HasForeignKey("CorrectsNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_notes_corrects");

                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_notes_customer");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Profile.CustomerProfile", b =>
                {
                    b.OwnsOne("GridCore.Modules.Customers.Features.ServiceLocations.Address", "MailingAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("mailing_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("mailing_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("mailing_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("mailing_region");

                            b1.HasKey("CustomerProfileCustomerId");

                            b1.ToTable("customer_profiles", "customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileCustomerId");
                        });

                    b.Navigation("MailingAddress");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_customer");

                    b.HasOne("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", null)
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_accounts_location");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccountHistoryEntry", b =>
                {
                    b.HasOne("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", null)
                        .WithMany("History")
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_account_history_account");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceLocations.ServiceLocation", b =>
                {
                    b.OwnsOne("GridCore.Modules.Customers.Features.ServiceLocations.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ServiceLocationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_region");

                            b1.HasKey("ServiceLocationId");

                            b1.HasIndex("Region")
                                .HasDatabaseName("ix_service_locations_address_region");

                            b1.ToTable("service_locations", "customers");

                            b1.WithOwner()
                                .HasForeignKey("ServiceLocationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.Contacts.CustomerContact", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("GridCore.Modules.Customers.Features.ServiceAccounts.ServiceAccount", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
